### ISSUE TITLE
Do not generate config.sh when there are no changes

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/keg#115]
When there are no changes to the scriptlets keg still generates config.sh. The file gets a new generated time stamp in the file, but the change is superfluous, we should not generate the file if there are no material changes.

**Comment by jgleissner** [comment]
This isn't quite as straight-forward as it sounds. Keg simply generates files based on input. It doesn't know about changes per-se. The `compose_kiwi_description` script used with the OBS source service has some idea of changes between image descriptions, but it's limited to extracting the image version from `config.kiwi` and checking whether the source repo has new commits and whether the `generate_changelog` command produced new entries. It doesn't have any deeper knowledge about the generated content. It would certainly be possible to implement a special check for config.sh diffing only the part below the header to catch this case, and then delete only the newly generated config.sh to avoid OBS copying over the old one. That seems a bit hacky to me, especially considering that the sole purpose is just to avoid a new time stamp in the file.

We could simply drop the time stamp from the config.sh header. The file's time stamp would still change but it wouldn't result in a diff in OBS.

**Comment by rjschwei** [comment]
I am OK with dropping the time stamp. It may be advantageous to drop the information from config.kiwi as well and write a separate file that contains the information about the latest image description generation. While theoretically we would bump the version every time the image gets generated and as such the timestamp in config.kiwi does not generate a "diff because of timestamp" separating the generation time information from the image description content is probably a good idea in general.

**Comment by jgleissner** [comment]
Implementation merged.
