### ISSUE TITLE
create scripts without a template engine

### ISSUE THREAD

**Issue by schaefi** [SUSE-Enceladus/keg#39]
If you look at the templates config.sh.templ and images.sh.templ you will see that they almost completely just traverse a dictionary and print the data. There is no semantic or syntax that the template would enforce. Thus creating the same file with just python would mean reading of the dict and writing its values into a file.

From that perspective the creation of the script code could be done simpler and without a template engine in between

**Comment by jgleissner** [comment]
Forgot to close this, sorry.
