### ISSUE TITLE
Add examples to keg --help output

### ISSUE THREAD

**Issue by aosthof** [SUSE-Enceladus/keg#70]
It's not always straight forward to construct a valid keg command call. Add some examples to "keg --help" like they're available in the manpage. 

General example:

          $ git clone https://github.com/SUSE-Enceladus/keg-recipes.git

          $ keg --recipes-root keg-recipes --dest-dir leap_description leap/jeos/15.3

Example for -a: "--add-data-root=additional-keg-recipes/data"

Example for -i: "--image-version=1.0.0"

**Comment by jgleissner** [comment]
I think it's not common to have examples in the usage output. The man page is more appropriate, and as you say, it already has an example, albeit simple. I think it's fine. Ok to close this @aosthof ?

**Comment by rjschwei** [comment]
I agree, examples belong in the man page.

**Comment by jgleissner** [comment]
Closing old issue.
