### ISSUE TITLE
Command line arg "-l" not working

### ISSUE THREAD

**Issue by t-ru** [SUSE-Enceladus/keg#87]
`keg -r /home/a001480/keg-recipes --list-recipes`

okay

`keg -r /home/a001480/keg-recipes --list`

"--list" does not exist in the command help... but is working

`keg -r /home/a001480/keg-recipes -l`

[ ERROR   ]: 19:35:53 | Unexpected error:
Traceback (most recent call last):
  File "/usr/local/bin/keg", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/kiwi_keg/keg.py", line 100, in main
    image_generator = KegGenerator(
  File "/usr/local/lib/python3.8/site-packages/kiwi_keg/generator.py", line 47, in __init__
    if not os.path.isdir(dest_dir):
  File "/usr/lib64/python3.8/genericpath.py", line 42, in isdir
    st = os.stat(s)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by jgleissner** [comment]
I assume docopt accepts sub-strings for options as long as they are unique, so `--list` would be expanded to `--list-recipes`. The short version `-l` was buggy but that was fixed quite a while ago.

**Comment by t-ru** [comment]
Nice, that it was fixed a while ago. The SUSE documentation recommends installing via https://pypi.org/. 
On https://pypi.org only version 0.0.6 is available. Current ist 1.1.0. Maybe you should update https://pypi.org/

**Comment by jgleissner** [comment]
True, the pypi version is very out of date. New version is coming soon, will update pypi then as well.
