### ISSUE TITLE
 The .virtualenv.requirements.txt does not install jing, this should be added as a system package requirement in the README

### ISSUE THREAD

**Issue by KeithMnemonic** [SUSE-Enceladus/keg#93]
When following the readme, running this command 

pip install -r .virtualenv.dev-requirements.txt

installs kiwi-ng in the tox virtualenv but it does not install jing.  Because of this when using keg and you encounter a syntax error you get the following error.

`[ INFO    ]: 16:58:52 | Using KIWI schema: vm
[ INFO    ]: 16:58:52 | Support for multiple markup descriptions available
[ WARNING ]: 16:58:53 | Command "jing" not found in the environment
[ WARNING ]: 16:58:53 | For detailed schema validation report, install: jing
[ INFO    ]: 16:58:53 | Showing only raw library error log:
[ INFO    ]: 16:58:53 | --> /var/tmp/kiwi_xslt-evj8824k:54:0:ERROR:RELAXNGV:RELAXNG_ERR_INTERSEQ: Invalid sequence in interleave
/var/tmp/kiwi_xslt-evj8824k:54:0:ERROR:RELAXNGV:RELAXNG_ERR_CONTENTVALID: Element packages failed to validate content
<string>:0:0:ERROR:RELAXNGV:RELAXNG_ERR_INTEREXTRA: Extra element packages in interleave
/var/tmp/kiwi_xslt-evj8824k:54:0:ERROR:RELAXNGV:RELAXNG_ERR_CONTENTVALID: Element image failed to validate content
[ ERROR   ]: 16:58:53 | KegKiwiValidationError: Failed to validate image description: Failed to validate schema and/or schematron rules. Use --debug for more details
`

As jing is a system package and it is not possible to install via pip, this additional requirement should be added to the top level README

**Comment by t-ru** [comment]
I'm using keg on opensuse 15.3 @ wsl2. here my install commands:

zypper install -y python3-pip
zypper install -y jing
zypper install -y xerces-j2
pip install wheel
pip install jinja2
pip install anymarkup
#pip install kiwi-keg
cd ~/
git clone https://github.com/SUSE-Enceladus/keg
cd ~/keg
python3.6 setup.py install
cd ~
rm -rf ~/keg

**Comment by jgleissner** [comment]
Requirement added to README with https://github.com/SUSE-Enceladus/keg/pull/108.
